site_name: Luis Alvaro Saenz Portfolio
site_url: https://embedded-systems-design.github.io/EGR314DataSheetTemplate
repo_url: https://github.com/embedded-systems-design/EGR314DataSheetTemplate
edit_uri: edit/main/docs/
theme:
  name: material
  #custom_dir: custom_theme/partials
  palette:
    primary: black
    accent: indigo
  font:
    text: Roboto
  logo: static/squid.svg
  favicon: static/squid.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.overflow
    - toc.follow    
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.action.edit
    - navigation.footer
#    - navigation.sections
    - navigation.expand
#    - navigation.instant # doesn't work that well

markdown_extensions:
  - attr_list #add attributes using curly brackets to images, see https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html # see https://squidfunk.github.io/mkdocs-material/reference/images/
  - footnotes
  - admonition
  - pymdownx.details #comment out if no work
  - pymdownx.mark # comment out if no work
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

draft_docs: |
  **/*_unpublished.md
  **/*_draft.md
  **/*_draft**
  
plugins:
  - search
  - glightbox # allow resize images, see https://squidfunk.github.io/mkdocs-material/reference/images/

extra_css:
  - stylesheets/extra.css  

extra_javascript:
 - javascripts/mathjax.js
 - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
not_in_nav: |
  static
  subfolder
  
  
copyright: "Copyright &copy; 2026 team-name-here"

extra:
  generator: false
  social:
    - icon: fontawesome/regular/file-code
      link: /2026_spring
      name: 2023 Site    

nav:
  - Home: index.md
  #- Requirements: 01-Requirements/Requirements.md
  #- Block Diagram: 02-Block-Diagram/Block-Diagram.md
  #- Component Selection: 03-Component-Selection/Component-Selection.md
  #- Power Budget: 10-Power-Budget/Power-Budget.md
  #- Schematic: 05-Schematic/schematic.md
  #- BOM: 04-BOM/BOM.md
  #- Reflection: 09-Reflection/Reflection.md
  - Appendix: Appendix/index.md
  - Projects: Projects/projects.md
      #- A1 Component Selection: Component-Selection/Component-Selection-Process.md
      #- A2a Microcontroller Selection: 02-Microcontroller-Selection/esp-32-table.md
      #- A2b Microcontroller Selection: 02-Microcontroller-Selection/pic-table.md
      #- A3 Component Selection: Component-Selection/Component-Selection-Process.md
      #- A4a Examples to Remove: 04-Examples-to-Remove/another-subfile.md
      #- A4b Examples to Remove: 04-Examples-to-Remove/charts.md
  #- Examples to Remove: 04-Examples-to-Remove/basic-markdown-examples.md

